### ISSUE TITLE
findstu: no way to search for names with spaces

### ISSUE THREAD

**Issue by jontmy** [jontmy/pe#6] opened 2022-11-11 08:44 UTC
It is unclear in the user guide whether all keywords must match or any keyword.

### Steps to Reproduce

```
clear
addstu n/Alice A h/@alicea e/alice18@gmail.com
findstu Alice B
```

### Expected Behavior
Shouldn't return any results, as the name doesn't match.

### Actual Behavior
Returns Alice A.

### Screenshots

![Screenshot 2022-11-11 at 16.43.54.png](https://raw.githubusercontent.com/jontmy/pe/master/files/d7ded498-31c4-4fea-af19-1003710f7624.png)

![Screenshot 2022-11-11 at 16.44.16.png](https://raw.githubusercontent.com/jontmy/pe/master/files/efb9dfe2-7abf-4a5e-af8d-7a85fbc70d6a.png)

**Comment by nus-se-script** [comment] 2022-11-14 21:12
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
No details provided by team.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Lack of description for the findstu command in UG
>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/9af8a10b-4919-4726-95df-110b77a3f950.png)
>
>As shown above, there is no info on how the findstu command matches the keywords.
>
>This might be problematic in such cases like some users might assume that it will only find users with the exact same name (e.g. `Alice` will match `Alice` and not `Aliceeee`) while others expect for the keyword to only be found on the name (e.g. `Alice` will match both `Alice` and `AAAAAAliceeeeeeeeeee`
>
>
>
>
><hr>
><sub>[original: nus-cs2103-AY2223S1/pe-interim#5752] [original labels: severity.Medium type.DocumentationBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>As mentioned in the first point, the command finds student with specified keyword in their name,   as long as the keyword exist in the name, it will list out the student.

# Items for the Tester to Verify

## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------

## :question: Issue response

Team chose [`response.Rejected`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------

## :question: Issue type

Team chose [`type.DocumentationBug`]
Originally [`type.FeatureFlaw`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------

**Closed** 2023-04-09 02:30 UTC
Labels: type.FeatureFlaw, severity.Low, status.Done
