### ISSUE TITLE
unhelpstu: incorrect error message when unhelping an unhelped student

### ISSUE THREAD

**Issue by jontmy** [jontmy/pe#4] opened 2022-11-11 08:33 UTC
### Steps to Reproduce

```
clear
addstu n/Alice A h/@alicea e/alice18@gmail.com
unhelpstu 1
```

### Expected Behavior
An error message which says which index of the student that cannot be unhelped.

### Actual Behavior
Got this message: "Help tag for %1$s is non-existent", probably typo'd a `%d` in the code. 

### Screenshots

![Screenshot 2022-11-11 at 16.33.31.png](https://raw.githubusercontent.com/jontmy/pe/master/files/891515cb-b6a2-4eac-a0a3-b155a93872e0.png)

**Comment by nus-se-script** [comment] 2022-11-14 20:12
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
No details provided by team.

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Incorrect error message when removing non-existent help tag
>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/5827d33d-038e-4392-96db-4b3971e63a8e.png)
>
>Input : unhelpstu 4
>Expected : Help tag for John Lim Jun Jie is non-existent
>Actual : Help tag for %1$s is non-existent
>
>The error message is unclear, and does not display the student's name when you try to remove a non-existent help tag for that student.
>
>
>
>
><hr>
><sub>[original: nus-cs2103-AY2223S1/pe-interim#4148] [original labels: severity.Medium type.FunctionalityBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>it does not affect normal operations of the product

# Items for the Tester to Verify

## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------

**Closed** 2023-04-09 02:30 UTC
Labels: type.FunctionalityBug, severity.Low, status.Done
