### ISSUE TITLE
editstu: no 0-padding for numbers seems dubious

### ISSUE THREAD

**Issue by jontmy** [jontmy/pe#12] opened 2022-11-11 09:21 UTC
Given that the attendance is an `int` value, and every other command accepts a `0`-padded `int` value (such as indices), this seems like an application bug disguised as a dubious requirement.

![Screenshot 2022-11-11 at 17.21.16.png](https://raw.githubusercontent.com/jontmy/pe/master/files/2f7e5bf7-a709-4e58-a875-9528076aeb1b.png)

**Comment by nus-pe-script** [comment] 2022-11-15 01:07
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
Same error

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Can set attendance to have leading zeros
>
>According to the UG,
>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/b9bfed02-a4d8-423a-9c67-c023bdecad65.png)
>
>Hence, I believe that one would expect an error when such a value is inputted. However if you add a student and do `editstu 1 a/000000010000000` it would result in the following.
>
>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/5a9c48ac-91e5-4d40-8227-322c62b494fe.png)
>
>
>
>
>
>
><hr>
><sub>[original: nus-cs2103-AY2223S1/pe-interim#5647] [original labels: type.FunctionalityBug severity.Low]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>The UG specifies that this will not be supported.

# Items for the Tester to Verify

## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------

## :question: Issue response

Team chose [`response.NotInScope`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------

## :question: Issue type

Team chose [`type.FunctionalityBug`]
Originally [`type.DocumentationBug`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------

**Closed** 2023-04-09 02:30 UTC
Labels: type.DocumentationBug, severity.Low, status.Done
