### ISSUE TITLE
dg: weird star symbols

### ISSUE THREAD

**Issue by jontmy** [jontmy/pe#17] opened 2022-11-11 09:34 UTC
Probably should have been bolded at Model component section, "** API**" , compare with the bolded "API" below.

![Screenshot 2022-11-11 at 17.35.27.png](https://raw.githubusercontent.com/jontmy/pe/master/files/5fd8db64-2be0-413a-9edb-02431d30907d.png)

**Comment by nus-se-script** [comment] 2022-11-15 02:14
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
Same error

## The 'Original' Bug

[The team marked this bug as a duplicate of the following bug]

># Typo in DG #1
>
>**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
>![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/54ba6839-6819-405d-9c28-6fea7109fc62.png)
>
>As above, I think it is meant to be **`API`** (bolded).
>
>
>
>
>
><hr>
><sub>[original: nus-cs2103-AY2223S1/pe-interim#5758] [original labels: severity.VeryLow type.DocumentationBug]</sub>
>
>
>

## Their Response to the 'Original' Bug

[This is the team's response to the above 'original' bug]

>No details provided by team.

# Items for the Tester to Verify

## :question: Issue duplicate status

Team chose to mark this issue as a duplicate of another issue (as explained in the _**Team's response**_ above)

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------

**Closed** 2023-04-09 02:30 UTC
Labels: type.DocumentationBug, severity.VeryLow, status.Done
